export const MIB = 1024 * 1024;
export const MAX_LEGACY_LIVE_QR_INPUT_BYTES = 1 * MIB;
export const MAX_LIVE_QR_INPUT_BYTES = 2 * MIB;
export const MAX_EXPERIMENTAL_LIVE_QR_INPUT_BYTES = 25 * MIB;
export const MAX_LIVE_QR_METADATA_BYTES = 16 * 1024;
export const LQP1_PREFIX_BYTES = 8;
export const MAX_LIVE_QR_PACKAGE_BYTES = (
  MAX_LIVE_QR_INPUT_BYTES + MAX_LIVE_QR_METADATA_BYTES + LQP1_PREFIX_BYTES
);
export const MAX_LEGACY_LIVE_QR_PACKAGE_BYTES = (
  MAX_LEGACY_LIVE_QR_INPUT_BYTES + MAX_LIVE_QR_METADATA_BYTES + LQP1_PREFIX_BYTES
);
